### ISSUE TITLE
当前最新代码的事件绑定失效

### ISSUE THREAD

**Issue by weibangtuo** [AlloyTeam/AlloyGameEngine#3]
当前Master分支中的代码绑定事件不会触发到，麻烦库主尽快修复。另几个Demo希望更新，由于使用了ARE代替原are全局变量，好几个demo跑不起来。若可以，整理一份API文档就更好了，没有API文档，都不知道有什么API，只能边写边看源码，效率低下。

**Comment by kmdjs** [comment]
@weibangtuo  目前所有demo已经能够正常跑起来。你说的绑定事件不会触发是指？ API文档正在整理当中~~~

**Comment by weibangtuo** [comment]
```
 var stage = new ARE.Stage("#canvas"),
            playingFrame = 13;
        var ld = new ARE.Loader();

        ld.loadRes([
                    { id: "fullscreen", src: "fullscreen.png" }]
        );

        ld.complete(function () {
            var fullScreenBmp = new ARE.Bitmap(ld.get('fullscreen'));
            fullScreenBmp.scaleY = fullScreenBmp.scaleX = 0.1;
            fullScreenBmp.x = 434;
            fullScreenBmp.y = 23;
            fullScreenBmp.onClick(function () {
                //do sth
            });
            stage.add(fullScreenBmp);
        });
```

onClick不会触发，或者不使用Loader也不会触发。

**Comment by kmdjs** [comment]
@weibangtuo  你的代码和 http://alloyteam.github.io/AlloyGameEngine/example/bitmap.html 没有太大区别啊。都能触发事件啊。=   =！

**Comment by weibangtuo** [comment]
我也觉得奇怪，demo是可以触发的，难道因为我使用的图片太多？我共使用的28张图片，稍后我再贴上代码

**Comment by weibangtuo** [comment]
http://121.42.146.130/html5/are/exmple1.html
这是做3D的，在给视频右上角黑色的部分绑定事件，点击时全屏，但绑定的事件方法没有执行，麻烦调试一下。

**Comment by kmdjs** [comment]
@weibangtuo  请不要给canvas指定如下样式：
        #ourCanvas{
            display: block;
            width: 100%;
            height: 100%;
        }
如果一定要撑满屏幕。
请使用stage.scaleToScreen(1,1);
如scaleToScreen的例子：
http://alloyteam.github.io/AlloyGameEngine/example/scalable.html

**Comment by weibangtuo** [comment]
额，好吧，希望文档中有明显的提示说明，害得我调试半天都不知道为啥。

**Comment by lujq1020** [comment]
`loader.loadRes([{ id: 'bgm', src: 'sound/bgm1.mp3' }]);`
使用loader加载MP3文件时候，提示
`Uncaught TypeError: self.handleProgress is not a function  .... are.js:357`

**Comment by kmdjs** [comment]
@lujq1020  已经修复，多谢反馈。
